spring:
  application:
    name: Skillify-Me-Course
  data:
    mongodb:
      uri: mongodb+srv://developersouvik02:XuslpqBEKNFWaH5Z@skillify.tzsm6tm.mongodb.net/?retryWrites=true&w=majority&appName=Skillify
      database: SkillifyMe
      auto-index-creation: true
      username: developersouvik02
      password: XuslpqBEKNFWaH5Z
server:
  PORT: 8081
